Repository wecode-bootcamp-korea/17-1st-WeGotDiz-frontend, pull requests merged in 2021-02, with the labels that each got.

#2 [17기 이정민] 공통 Footer 레이아웃 구성 및 컴포넌트화 완료 !
  .eslintrc
  .gitattributes
  .prettierrc
  src/Component/Footer/Component/FooterInfo.js
  src/Component/Footer/Component/FooterMenu.js
  src/Component/Footer/Component/FooterMenuData.js
  src/Component/Footer/Component/FooterNotice.js
  src/Component/Footer/Footer.js
  src/Component/Footer/Footer.scss
Labels: Status: 리뷰 요청

#1 [17기 이정민] 피드백 반영 완료 / 검색 기록 추가 기능 구현중 / 로그인 로그아웃 프로필사진 버튼 기능 추가
  public/favicon.png
  public/images/logo.PNG
  public/images/userPhoto.png
  public/images/wegotdizLogo.svg
  public/index.html
  src/Components/Footer/Components/FooterMenu.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/Components/SearchText.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#3 [17기 이사랑] 제품 상세 페이지 컴포넌트 리뷰 반영 완료 + merge 요청
  public/data/makerInfoData.json
  public/data/productData.json
  src/Components/Nav/Nav.scss
  src/Pages/Product/Components/Aside/Aside.js
  src/Pages/Product/Components/Aside/Aside.scss
  src/Pages/Product/Components/Community/Community.js
  src/Pages/Product/Components/Community/Community.scss
  src/Pages/Product/Components/Header/Header.js
  src/Pages/Product/Components/Header/Header.scss
  src/Pages/Product/Components/Policy/Policy.js
  src/Pages/Product/Components/Policy/Policy.scss
  src/Pages/Product/Components/Story/Story.js
  src/Pages/Product/Components/Story/Story.scss
  src/Pages/Product/Components/Tabs/Tabs.js
  src/Pages/Product/Components/Tabs/Tabs.scss
  src/Pages/Product/Product.js
  src/Pages/Product/Product.scss
  src/Pages/Purchase/Purchase.js
Labels: Status: Accepted

#5 [17기 허혜성] 로그인 코드 리팩토링
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
Labels: Status: Accepted

#4 [17기 허혜성] 회원가입 코드 리팩토링
  .eslintrc
  .vscode/settings.json
  src/Components/Nav/Nav.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
Labels: Status: Accepted

#9 [17기 이사랑] 결제 페이지 컴포넌트화 1차 완료
  public/data/alertInfoData.json
  public/data/purchaseData.json
  public/data/userInfoData.json
  src/Pages/Purchase/Components/AlertInfo/AlertInfo.js
  src/Pages/Purchase/Components/AlertInfo/AlertInfo.scss
  src/Pages/Purchase/Components/AlertModal/AlertModal.js
  src/Pages/Purchase/Components/AlertModal/AlertModal.scss
  src/Pages/Purchase/Components/CheckboxRect/CheckboxRect.js
  src/Pages/Purchase/Components/CheckboxRect/CheckboxRect.scss
  src/Pages/Purchase/Components/CheckboxRound/CheckboxRound.js
  src/Pages/Purchase/Components/CheckboxRound/CheckboxRound.scss
  src/Pages/Purchase/Components/ChooseReward/ChooseReward.js
  src/Pages/Purchase/Components/ChooseReward/ChooseReward.scss
  src/Pages/Purchase/Components/InputRect/InputRect.js
  src/Pages/Purchase/Components/InputRect/InputRect.scss
  src/Pages/Purchase/Components/InputRound/InputRound.js
  src/Pages/Purchase/Components/InputRound/InputRound.scss
  src/Pages/Purchase/Components/List/List.js
  src/Pages/Purchase/Components/List/List.scss
  src/Pages/Purchase/Components/ProductHeader/ProductHeader.js
  src/Pages/Purchase/Components/ProductHeader/ProductHeader.scss
  src/Pages/Purchase/Components/PurchaseComplete/PurchaseComplete.js
  src/Pages/Purchase/Components/PurchaseComplete/PurchaseComplete.scss
  src/Pages/Purchase/Components/PurchaseReservation/PurchaseReservation.js
  src/Pages/Purchase/Components/PurchaseReservation/PurchaseReservation.scss
  src/Pages/Purchase/Components/PurchaseStep/PurchaseStep.js
  src/Pages/Purchase/Components/PurchaseStep/PurchaseStep.scss
  src/Pages/Purchase/Components/Reward/Reward.js
  src/Pages/Purchase/Components/Reward/Reward.scss
  src/Pages/Purchase/Purchase.js
  src/Pages/Purchase/Purchase.scss
  src/Pages/Purchase/thisPropsData.js
Labels: Status: 수정 요청

#8 [17기 허혜성] mypage 코드 리팩토링
  public/data/fundingData.json
  public/data/likeData.json
  public/data/myPageData.json
  src/Components/Nav/Nav.js
  src/Pages/Mypage/Components/Funded/FundList/FundList.js
  src/Pages/Mypage/Components/Funded/FundList/FundList.scss
  src/Pages/Mypage/Components/Funded/Funded.js
  src/Pages/Mypage/Components/Funded/Funded.scss
  src/Pages/Mypage/Components/Liked/LikeList/LikeList.js
  src/Pages/Mypage/Components/Liked/LikeList/LikeList.scss
  src/Pages/Mypage/Components/Liked/Liked.js
  src/Pages/Mypage/Components/Liked/Liked.scss
  src/Pages/Mypage/Components/MypageHeader.js
  src/Pages/Mypage/Components/MypageHeader.scss
  src/Pages/Mypage/Mypage.js
  src/Pages/Mypage/Mypage.scss
  src/Pages/Product/Product.js
  src/Pages/Purchase/Components/PurchaseReservation/PurchaseReservation.js
  src/Pages/Purchase/Purchase.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/config.js
Labels: Status: 수정 요청
